### PR TITLE
[Website] API Accessibility

### PR DESCRIPTION
**Pull request by NubbyTM**
Done:
– Added UI for player info
– Added method of authentication via api.mineplex.com/auth.php
– Added ability to find player in index.html

To-Do in future:

– Network Information
   • See laggiest servers with a graph
   • Ability to access the lag of a server
   • If a lobby is detected lagging, the lobby gadgets will shut down by themselves
– Amplifier Information on all games
– Brawl Information

**NOTE:** While this seems to "break the purpose" of a public API, I think it should be added because if people want to know basic information about a player, they can do it directly without having to visit another API webpage.

### CODE REVIEW

**Comment by WilliamBurns** [comment]
What does this actually do?

**Comment by NubbyTM** [comment]
@WilliamBurns This will allow people, when they visit api.mineplex.com to use their auth key and get information about players. For example, if I searched my IGN, NubbyTM, I would find my rank and level. I will add more statistics, but I want it to be an easy way to make sure your API Key works.

**Comment by WilliamBurns** [comment]
We already have a version of this in the docs at https://api.mineplex.com/pcdocs/ - people can authenticate and try out their API key by clicking "Authorize" (top right of the page).

**Comment by NubbyTM** [comment]
@WilliamBurns Oh, but either way, why not have something like that? It would be a nice and elegant way to display information. Also, in the future, we could get the owner of the API Key and look at their rank. We could then make it so admins would be able to stop gadgets on servers like Lobby-1 without having to go in-game and get yelled at by rioters.

**Comment by WilliamBurns** [comment]
The API is a tool for developers to make their own ways of displaying Mineplex information, not for us to do it for them.

**Pull request closed without merging**
