### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by DesWurstes**
Also can I get an API key? I'm not a webmaster or something (just a power user), but I can't wait for its release.

### CODE REVIEW

**Comment by OutdatedVersion** [comment]
quite the PR here

**Comment by phonyfakeorreal** [comment]
@DesWurstes You can't get a key (yet). They say there's an early access program, but there's really not.

**Comment by DesWurstes** [comment]
@phonyfakeorreal Yes there is. If not, how did Artix.cc get it?

**Comment by OutdatedVersion** [comment]
You're invited to the testing phase of the API; which is one way some people have keys already, @DesWurstes. Publicly accessible keys will be coming shortly.

**Comment by DesWurstes** [comment]
OK.

**Comment by WilliamBurns** [comment]
@DesWurstes @phonyfakeorreal Early access API keys are being given out. Join the [discord here](https://discord.gg/gzbfu) and ask for a key. You might get one!

**Pull request merged**
