### PR TITLE
Basic java example

### PR DESCRIPTION
**Pull request by phonyfakeorreal**
Implementation in Java using Gson library for simplicity. Didn't add URL functionality, just showing theoretical class usage.

### CODE REVIEW

**Comment by OutdatedVersion** [comment]
o ok phony :(

**Comment by phonyfakeorreal** [comment]
@OutdatedVersion Submit your pull anyway lol

**Comment by WilliamBurns** [comment]
This doesn't do anything (?)

**Comment by phonyfakeorreal** [comment]
I'll make it do stuff....

**Pull request closed without merging**
